### ISSUE TITLE
Using ace-builds with webpack

### ISSUE THREAD

**Issue by komali2** [ajaxorg/ace-builds#129]
We are trying to use ace-builds with webpack. 

We have used the line 

`    var Ace = require('ace-builds/src/ace');`

```
ERROR  Failed to compile with 91 errors                                                                                            12:26:03

These relative modules were not found:

* ../../lib/lang in ./node_modules/ace-builds/src/ace.js
* ../../lib/oop in ./node_modules/ace-builds/src/ace.js
<snip>
```

We have tried many iterations of "using ace editor with webpack," further documented on the [master ace-editor repo. ](https://github.com/ajaxorg/ace/issues/3654)

We worked on this a long time before making an issue in either place, I am doing so now because I have been unable to find a definitive resource on using either ace, ace-builds, or brace with webpack on a repo that uses custom modes. 

What is the proper way to use ace-builds with webpack?

**Comment by nightwing** [comment]
For backwards compatibility current version of ace-builds/src does not work with webpack.
But you can use `var ace = require('ace-builds');` or `var ace = require('ace-builds/src-noconflict/ace');`

There is a demo of using ace-builds with webpack at https://github.com/ajaxorg/ace/blob/master/demo/webpack/demo.js, please let me know if you have any questions about it, or have any suggestions on how to improve it.

**Comment by komali2** [comment]
This is great help, thank you for taking the time to reply. 

That sorts out a lot of the dependency errors we were getting from ace, but for custom modes we're still having trouble figuring it out. 

For example, when using ace without webpack (pure require.js), we would just

```
var TextMode = require("ace/mode/text").Mode;
var CStyleFoldMode = require("ace/mode/folding/cstyle").FoldMode;
```

However, I can't find, for example, mode/text in the ace-builds repo (or anything about cstyle)

Do you have any advice about this?

Once we sort this, I will be very happy to get together some suggestions on documentation for using custom modes with webpack. It's possible that my team and I are just missing something obvious, though!

**Comment by nightwing** [comment]
There only a hacky way of doing this for now.

use 

``` js
// load the javascript mode which contains cstyle helpers
require("ace-builds/src-noconflict/mode-javascript")
// use ace.require to get internal modules
var CStyleFoldMode = ace.require("ace/mode/folding/cstyle").FoldMode;
```

**Comment by komali2** [comment]
Ok, awesome, will try in a second. For the record, I tried also installing the entire ace-code-editor package alongside ace-builds, and for things like cstyle referring to them inside the ace-code-editor package, and got errors such as 

```
jQuery.Deferred exception: Cannot read property 'split' of undefined TypeError: Cannot read property 'split' of undefined
    at AppConfig.exports.moduleUrl (webpack-internal:///./node_modules/ace-builds/src-noconflict/ace.js:4368:22)
```

Just to dissuade anybody from going down that route. 

Will report back about above suggestion in new comment.

**Comment by komali2** [comment]
Appreciate the suggestion, this has given us a new avenue to explore. Had forgotten about ace.require (and the acequire equivalent of brace). 

Unfortunately, we're getting a similar error to above

```
jQuery.Deferred exception: Cannot read property 'split' of undefined TypeError: Cannot read property 'split' of undefined
    at AppConfig.exports.moduleUrl (webpack-internal:///./node_modules/ace-builds/src-noconflict/ace.js:4368:22)
```

Just the initial report, still digging to learn more. 

Thank you for all your help so far, we're getting further now than we have all week.

**Comment by komali2** [comment]
This error was my fault. 

The end of our custom mode file looked like

```
exports.Mode = Mode;

});
```

But I was only doing

`   var mode = require('@/lib/ace/mode/custom');`

I should have been doing

`   var mode = require('@/lib/ace/mode/electricimp').Mode;`

Then, later, i did  set_mode on `mode` directly, when I should have been doing

` session.setMode(new mode());`

Will comment will full setup momentarily. Thank you for your help @nightwing , I think we've got it sorted!

**Comment by komali2** [comment]
For those that come after:

1. `npm install ace-builds`

2. Change require statements to 

`    var Ace = require('ace-builds/src-noconflict/ace');`

3. Give up on dynamically importing themes, do

```
    var theme_idle_fingers = require('ace-builds/src-noconflict/theme-idle_fingers');
    var theme_github = require('ace-builds/src-noconflict/theme-github');
    editor.set_theme(theme_github)
```

4. At the top of your custom mode and custom highlight rules files, do

```
// load the javascript mode which contains cstyle helpers
require("ace-builds/src-noconflict/mode-javascript")
var Ace = require('ace-builds/src-noconflict/ace');
```

5. Then you can pull in component modes like

```
// defines the parent mode
var TextMode = Ace.require("ace/mode/text").Mode;
var CStyleFoldMode = Ace.require("ace/mode/folding/cstyle").FoldMode;
var CstyleBehaviour = Ace.require("ace/mode/behaviour/cstyle").CstyleBehaviour;
```

6. For posterity, highlight  rules works just like modes:

var Ace = require('ace-builds/src-noconflict/ace');

// load the javascript mode which contains cstyle helpers
require("ace-builds/src-noconflict/mode-javascript")

```
var oop = Ace.require("ace/lib/oop");
var DocCommentHighlightRules = Ace.require("ace/mode/doc_comment_highlight_rules").DocCommentHighlightRules;
var TextHighlightRules = Ace.require("ace/mode/text_highlight_rules").TextHighlightRules;
```

7. Make sure you are importing / exporting and doing `new` when necessary. If the end of your custom mode file looks something like

```
var Mode = function() {
    this.HighlightRules = CustomHighlightRules;

    this.$outdent = new MatchingBraceOutdent();
    this.$behaviour = new CstyleBehaviour();
    this.foldingRules = new CStyleFoldMode();
};
oop.inherits(Mode, TextMode);

(function() {
    //logic
}).call(Mode.prototype);

exports.Mode = Mode;

});
```

Then you need to do the following in your actual editor code:

`    var mode = require('@/lib/ace/mode/electricimp').Mode;`

`            session.setMode(new mode());`

**Comment by nightwing** [comment]
> Give up on dynamically importing themes, do

this is not nessesary
```js
import "ace-builds/webpack-resolver";
editor.setTheme('ace/theme/github');
```
as shown in https://github.com/ajaxorg/ace/blob/master/demo/webpack/demo.js#L12, should work.

**Comment by Ray-Eldath** [comment]
@XanderLuciano Many thanks! This certainly helps!
I think this issue could be closed.

**Comment by sumbria** [comment]
You can try this:
```
npm i ace-builds
```
```
import 'ace-builds';
import 'ace-builds/webpack-resolver';
```

```
ace.edit("editor", {
	mode: "ace/mode/html",
	theme: "ace/theme/dracula",
	maxLines: 50,
	minLines: 10,
	fontSize: 18
});
```
```
<div id="editor"></div>
```

**Comment by toasterpic** [comment]
> ```
> import 'ace-builds/webpack-resolver';
> ```

Bundles a lot of stuff not being used by this example, bloating your vendor.js. You could instead just import what you do need. In this example the following would be sufficient.

```
import * as ace from 'ace-builds'
import 'ace-builds/src-noconflict/mode-html'
import 'ace-builds/src-noconflict/theme-dracula'
```

**Comment by vdh** [comment]
`ace-builds/src-noconflict/worker-json.js` appears to have require issues in Webpack as well 😞

**Comment by tcstory** [comment]
> `ace-builds/src-noconflict/worker-json.js` appears to have require issues in Webpack as well

I used the following code and everything is ok

```
const Ace = require('ace-builds/src-noconflict/ace')
require('ace-builds/src-noconflict/mode-json5')
require('ace-builds/src-noconflict/theme-github')

    const editor = Ace.edit(this.$refs.editor, {
      mode: 'ace/mode/json5',
      theme: 'ace/theme/github',
      maxLines: 50,
      minLines: 10,
      fontSize: 18
    })

```
