### ISSUE TITLE
TypeError: Cannot read property 'getUndoManager' of null

### ISSUE THREAD

**Issue by fr0** [ajaxorg/ace-builds#171]
This is happening after upgrading from 1.4.7 to 1.4.8. Downgrading back to 1.4.7 "resolves" the issue.

```
TypeError: Cannot read property 'getUndoManager' of null
    at Editor.endOperation (http://localhost:9876/_karma_webpack_/node_modules/ace-builds/src-noconflict/ace.js:13244:1)
    at callback (http://localhost:9876/_karma_webpack_/node_modules/ace-builds/src-noconflict/ace.js:2117:1)
```

**Comment by hcl337** [comment]
Ping here - can someone merge this in? Definitely an issue which is hitting our usage of Ace.

**Comment by artvichi** [comment]
+1 we are having the same issue , fix it please!

**Comment by yegor-sytnyk** [comment]
+1, please merge :)

**Comment by Ujrep** [comment]
+1,  merge please

**Comment by andresmgot** [comment]
+1, can you please release a new version?
