### ISSUE TITLE
getMatchingTags get error when trying to fold in Html

### ISSUE THREAD

**Issue by calebeaires** [ajaxorg/ace-builds#237]
Using ace from ace non conflite and while trying to fold in mode-html, I get this error

Version: [1.16.0](https://github.com/ajaxorg/ace/compare/v1.14.0...v1.16.0) (2023-03-17)
Using Vue
Simple import and simple create instance

```
Uncaught TypeError: session.getMatchingTags is not a function
    at exports2.FoldMode.getFoldWidgetRange (mode-html.js:1805:28)
    at exports2.FoldMode.getFoldWidgetRange (mode-html.js:1711:21)
    at Folding.$toggleFoldWidget (ace.js:8920:30)
    at Folding.onFoldWidgetClick (ace.js:8895:30)
    at Array.<anonymous> (ace.js:4081:36)
    at EventEmitter._emit.EventEmitter._dispatchEvent (ace.js:3438:29)
    at MouseHandler.onMouseEvent (ace.js:3932:25)

```

```js

    mounted() {
        this.$nextTick(() => {
            ace.config.set('basePath', './');
            ace.config.setModuleUrl('ace/mode/json_worker', jsonWorkerUrl);
            ace.config.setModuleUrl('ace/mode/javascript_worker', jsWorkerUrl);
            ace.config.setModuleUrl('ace/mode/css_worker', cssWorkerUrl);
            ace.config.setModuleUrl('ace/mode/html_worker', htmlWorkerUrl);

            this.editor = ace.edit(this.id, {
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true,
                highlightActiveLine: true,
                enableEmmet: true,
                sharedPopups: false,
                scrollPastEnd: true,
                selectionStyle: 'text',
                showPrintMargin: false
            });

            this.editor.setKeyboardHandler('ace/keyboard/vscode');
            this.editor.$blockScrolling = Infinity;

            this.editor.getSession().on('change', this.emitCode);
            this.editor.getSession().setMode(`ace/mode/${this.$props.type}`);
            this.editor.setTheme(this.currentTheme);

            const self = this;
            this.editor.commands.addCommand({
                name: 'beautify',
                description: 'Format selection (Beautify)',
                exec: function (editor) {
                    self.beautifyCode();
                },
                bindKey: 'Ctrl-Shift-B'
            });

            this.editor.on('changeSelection', () => {
                this.$emit('select', this.editor.getSelectedText());
            });

            this.editor.setFontSize(this.$props.fontSize || '14px');

            setTimeout(() => {
                this.editor.getSession().setValue(`${this.$props.modelValue}`);
                this.editor.resize();
            });
        });
    }
```

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace-builds contains only builds, so I'm moving this issue to the repo with actual ace code https://github.com/ajaxorg/ace
