### ISSUE TITLE
ace-builds:1.22.0 & angular 16 not working

### ISSUE THREAD

**Issue by sysmat** [ajaxorg/ace-builds#245]
- "ace-builds": "^1.21.1" & angular 16 work fine
- ace-builds:1.22.0 & angular 16, there are errors:

```
polyfills.eaa7662fc47025ef.js:1 Uncaught TypeError: e is not a function
    at new r (scripts.d2b97a699bea8ee7.js:1:554509)
    at f.$init (scripts.d2b97a699bea8ee7.js:1:562635)
    at f.openPopup (scripts.d2b97a699bea8ee7.js:1:564298)
    at f.<anonymous> (scripts.d2b97a699bea8ee7.js:1:568465)
    at f.<anonymous> (scripts.d2b97a699bea8ee7.js:1:573737)
    at f.provideCompletions (scripts.d2b97a699bea8ee7.js:1:573983)
    at f.updateCompletions (scripts.d2b97a699bea8ee7.js:1:567940)
    at f.showPopup (scripts.d2b97a699bea8ee7.js:1:566755)
    at Array._ (scripts.d2b97a699bea8ee7.js:1:578346)
    at r._signal (ace.js:1:57912)
```

**Comment by sysmat** [comment]
My mistake app was including cdnjs ace/1.4.5
