### ISSUE TITLE
Dependency on file-loader breaks builds on node.js 17+

### ISSUE THREAD

**Issue by just-boris** [ajaxorg/ace-builds#250]
File loader is a deprecated package which does not receive any upgrades: https://github.com/webpack-contrib/file-loader

Node.js 17+ changed in available hash functions, which affects file-loader. The build now fails with this error:

```js
ERROR in ./node_modules/ace-builds/src-noconflict/worker-yaml.js (./node_modules/file-loader/dist/cjs.js?esModule=false!./node_modules/ace-builds/src-noconflict/worker-yaml.js)
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at getHashDigest (/path/to/project/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /path/to/project/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/path/to/project/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/path/to/project/node_modules/file-loader/dist/index.js:29:48)
 @ ./node_modules/ace-builds/webpack-resolver.js 314:48-117
```

The core webpack fixed the issue already (https://github.com/webpack/webpack/issues/14532#issuecomment-955682484), but  file-loader is a frozen package and it won't be fixed. 

Node 16 is the only version which still works but it will reach EOL in September 2023, and then `ace-builds/webpack-resolver` will become unusable on any valid node

**Comment by nightwing** [comment]
webpack-resolver.js is kept mainly for backwards compatibility, with new versions of node and webpack 5 you can use https://github.com/ajaxorg/ace-builds/blob/master/esm-resolver.js and use [ace-linters ](https://github.com/mkslanc/ace-linters) for syntax checking, which has much better support for yaml

**Comment by just-boris** [comment]
Thanks, tried this option using ace-builds@1.23.1

it prints me the following error

```
Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:8080/worker-javascript.js' failed to load.
    at handleError (http://127.0.0.1:8080/vendors.js:99762:58)
    at http://127.0.0.1:8080/vendors.js:99781:7
```

It fails with `ace-builds/esm-resolver`, when I change it back to `ace-builds/webpack-resolver`, it passes without any other changes in the code

**Comment by nightwing** [comment]
yes, the workers are not supported with esm-resolver, 
you need to set option `useWorker: false` to the editor and use ace-linters, which provides more flexible way of creating the worker.

**Comment by nightwing** [comment]
here's an example using this method https://github.com/ajaxorg/ace-samples/blob/master/samples/ace-builds-webpack/src/index.js
